server: "hub-cloud.browserstack.com"
user: "BROWSERSTACK_USERNAME"
key: "BROWSERSTACK_ACCESS_KEY"

common_caps:
  "build": "Watir-BrowserStack"
  "name": "Local Test"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
    "os": "Windows"
    "os_version": "7"
    "browserstack.local": true
