server: "hub-cloud.browserstack.com"
user: "BROWSERSTACK_USERNAME"
key: "BROWSERSTACK_ACCESS_KEY"

common_caps:
  "build": "Watir-BrowserStack"
  "name": "Parallel Test"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
    "os": "Windows"
    "os_version": "8"
  -
    "browser": "firefox"
    "os": "Windows"
    "os_version": "8"
  -
    "browser": "chrome"
    "os": "OS X"
    "os_version": "El Capitan"
  -
    "browser": "firefox"
    "os": "OS X"
    "os_version": "El Capitan"
